name: Test on Push(Linux)

on:
  pull_request:

jobs:
  test:
    uses: surface0/unity-ci-actions/.github/workflows/test-linux.yml@v1
    with:
      container-image: registry.internal.syn-sophia.net/<project>/unityci/editor:<tag>  # TODO: イメージを変更してください
      platform: EditMode
    secrets:
      unity-license: ${{ secrets.UNITY_LICENSE_LINUX }}