name: Test on Push(Windows)

on:
  pull_request:

jobs:
  test:
    uses: synSophia/ss-fleet-ci/.github/workflows/test-windows.yml@v1
    with:
      platform: EditMode
    secrets:
      unity-license: ${{ secrets.UNITY_LICENSE_WINDOWS }}
