name: 'Get Unity Version'
description: 'Get Unity version from ProjectVersion.txt and set it as an output.'
outputs:
  unity-version:
    description: "The Unity version string."
    value: ${{ steps.get_version.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: get_version
      run: |
        if command -v cygpath > /dev/null 2>&1; then
          action_path=$(cygpath -u "${{ github.action_path }}")
        else
          action_path="${{ github.action_path }}"
        fi
        version=$(python "$GITHUB_WORKSPACE/.github/ss-fleet-ci/scripts/get_unity_version.py")
        echo "version=$version" >> $GITHUB_OUTPUT
      shell: bash
