name: スペルチェック

on:
  workflow_call:

jobs:
  cspell:
    name: スペルチェック
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウトする
        uses: actions/checkout@v4

      - name: CSpell を実行する
        uses: synSophia/ss-fleet-ci/actions/cspell@v1
